replicaCount: 1
image:
  repository: ghcr.io/fitnest-backend/terabox-worker-service
  tag: "development-86dd373"
  pullPolicy: Always
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 9090
istio:
  enabled: true
  mtls:
    mode: STRICT
  authorization:
    internalCallers:
      - "cluster.local/ns/fitnest-dev/sa/user-service"
      - "cluster.local/ns/fitnest-dev/sa/media-service"
env:
  TERABOX_NDUS: "Yb8V8X8peHuio3Fg47cs5J-Xu0PN0eQlPpz-cYYm"
  TERABOX_APP_ID: "250528"
  TERABOX_JS_TOKEN: "EEAA220681598B4B9F065E950B04E2B0B86C83FE21640648FE96C0A179DEF9971F2F3458FD24A0330A2F450B8CB7BE59D17B19EA0C2ED36576F75E7F8BCF3DF077786C1E054D44211CD5BB8D3D9A76A1BA9B1FA92A97D2D8C52BC170F39829EF"
  TERABOX_BROWSER_ID: "1509IaJc0mCa5RYruyP3etYaUR3RwuBiZaDDEIpR4PUYFkT8WQlbFEZUS2Y="
  TERABOX_BDSTOKEN: "50051ebcccc591e6c9563c49f48cf892"
  TERABOX_BID_N: "19c53ecdd614fb75044207"
  TERABOX_NDUT_FMT: "69CF0DF8B1F1BB941A0B8BD48CD90FCD50302DB6FEEC92FC85512EAC48C52181"
  TERABOX_NDUT_FMV: "789b2bb424158a28622d4e20256d1e01864dabf54ad56025a410cf0b6355625fdd624b283ea668fc20957f02e19bb61b98c9e6930a0e0cf96c205e24eb7f6df306e65afd55df1cffb0f10b4b49cadfb3052481c7034fe189e3dcc29f918d5999d95394034f6c534983d23f5b80656c05"
  TERABOX_CSRF_TOKEN: "4-TZkxEZ3NAzGYCC6IshMTKW"
  TERABOX_WORKER_PORT: "9090"
  LOG_LEVEL: "info"
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
