replicaCount: 1
image:
  repository: ghcr.io/fitnest-backend/terabox-worker-service
  tag: "development-d3258e8"
  pullPolicy: Always
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 9090
istio:
  enabled: true
  mtls:
    mode: STRICT
  authorization:
    internalCallers:
      - "cluster.local/ns/fitnest-dev/sa/user-service"
      - "cluster.local/ns/fitnest-dev/sa/media-service"
env:
  TERABOX_NDUS: "Yb8V8X8peHuic_iDsmvygmFYU2GpHMQHsOHYULQk"
  TERABOX_APP_ID: "250528"
  TERABOX_JS_TOKEN: "BB04F91D937F292A33FB2D21F7B47DA9A04856DB210C0DAA286DE7F145C6D1244F428A4AABD88A9CE4AA1A6AFB7EFA97A7C8E43E05ABD53C5EF0D91A90ACC59B"
  TERABOX_BROWSER_ID: "1509IaJc0mCa5RYruyP3etYaUR3RwuBiZaDDEIpR4PUYFkT8WQlbFEZUS2Y="
  TERABOX_BDSTOKEN: "5d65e05181fad156b27206bf41f91d8c"
  TERABOX_BID_N: "19c53ecdd614fb75044207"
  TERABOX_NDUT_FMT: "7C32167A217DE17B9E2DEA2EC15B799BFFEB438A21F4A833334DA07259BFD465"
  TERABOX_NDUT_FMV: "f7639f25995717a37bef8af787b843baf46e83529dd7f79eabe7aa56b95fb6449e0f4309f4d4135acdfb49aa548a64ee8d96e622d7650369e2bc2e1a106daf8d4782a6cf23d73d96d0b1a532cafeb19f571711e39ea23605d38879b08b0addb54bfe3f382592bd807f2dfe9bbdf00c40"
  TERABOX_CSRF_TOKEN: "kO6cBP4LtPc2ZgfdEiW-su_z"
  TERABOX_WORKER_PORT: "9090"
  REDIS_HOST: "redis.fitnest-dev.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  LOG_LEVEL: "info"
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
