replicaCount: 1
image:
  repository: ghcr.io/fitnest-backend/terabox-worker-service
  tag: "development-d211c7f"
  pullPolicy: Always
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 9090
istio:
  enabled: true
  mtls:
    mode: STRICT
  authorization:
    internalCallers:
      - "cluster.local/ns/fitnest-dev/sa/user-service"
      - "cluster.local/ns/fitnest-dev/sa/media-service"
env:
  TERABOX_NDUS: "" # Set from GitHub secrets in CI/CD
  TERABOX_APP_ID: "250528"
  TERABOX_UPLOAD_ID: "" # Set from GitHub secrets in CI/CD
  TERABOX_JS_TOKEN: "" # Set from GitHub secrets in CI/CD
  TERABOX_BROWSER_ID: "" # Set from GitHub secrets in CI/CD
  TERABOX_BDSTOKEN: "" # Set from GitHub secrets in CI/CD
  TERABOX_USERNAME: "" # Set from GitHub secrets in CI/CD
  TERABOX_PASSWORD: "" # Set from GitHub secrets in CI/CD
  TERABOX_WORKER_PORT: "9090"
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
