apiVersion: v1
kind: Service
metadata:
  name: { { include "storage-service.fullname" . } }
  labels:
    { { - include "storage-service.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: 9090
      protocol: TCP
      name: grpc
  selector:
    { { - include "storage-service.selectorLabels" . | nindent 4 } }
